''' 
Author: Nguyen Phuc Minh
Lastest update: 8/3/2022
'''

SELF_CARE_CONFIDENCE = 5
GENERAL_PROCEDURE_CONFIDENCE = 10
EMERGENCE_CONFIDENCE = 15

# APPLICATION
FUZZY_THRESHOLD = 80  
EDIT_THRESHOLD = 3
SEMANTIC_THRESHOLD = 0.8 
COMPARE_METHOD = "fuzzy" # ['fuzzy','semantic','edit']

# APPLICATION - END CONDITION
MAXIMUM_TURN = 7
DISEASE_SEVERITY_CONFIDENCE = 10
DISEASE_DEFAULT_CONFIDENCE = 0.5

# Inference Engine
MAXIMUM_POSSIBLE_DISEASE=5