''' 
Author: Nguyen Phuc Minh
Lastest update: 22/2/2022
'''

SELF_CARE_CONFIDENCE = 5
GENERAL_PROCEDURE_CONFIDENCE = 10
EMERGENCE_CONFIDENCE = 15

# APPLICATION
FUZZY_THRESHOLD = 80  
EDIT_THRESHOLD = 3
SEMANTIC_THRESHOLD = 0.8 
COMPARE_METHOD = "fuzzy" # ['fuzzy','semantic','edit']

# APPLICATION - END CONDITION
MAXIMUM_TURN = 10
DISEASE_CONFIDENCE = 10